const _TOWERS = {

    laser:{
        type: "laser",
        buyCost: 25,
        sellPrice : 12,
        upgradePrice: 25,
        projectiles: false,
        boosts: false,
        speed: "very fast",
        description: "shoots lasers",
        upgradeDescription: null,
        slow: 0,
        damage: 1,
        secondaryDamage: 0,
        upgradeSecondaryDamage: 0,
        upgradeDamage: 0.50,
        upgradeRange: 5,
        upgradeSlow: 0,
        bonusDamage: 0,
        bonusSecondaryDamage: 0,
        bonusRange: 0,
        range: 80
    },

    slow:{
        type: "slow",
        buyCost: 50,
        sellPrice : 25,
        upgradePrice: 50,
        projectiles: false,
        boosts: false,
        speed: "very fast",
        description: "slows enemies",
        upgradeDescription: "increases slow",
        slow: 0.1,
        damage: 0.5,
        secondaryDamage: 0,
        upgradeSecondaryDamage: 0,
        upgradeDamage: 0.10,
        upgradeRange: 5,
        upgradeSlow: 0.05,
        bonusDamage: 0.05,
        bonusSecondaryDamage: 0,
        bonusRange: 0,
        range: 75
    },

    stop:{
        type: "stop",
        buyCost: 100,
        sellPrice : 50,
        upgradePrice: 50,
        projectiles: false,
        boosts: false,
        speed: "very slow",
        description: "stops an enemy",
        upgradeDescription: "increases range",
        slow: 1,
        damage: 0,
        secondaryDamage: 0,
        upgradeSecondaryDamage: 0,
        upgradeDamage: 0,
        upgradeRange: 5,
        upgradeSlow: 0.,
        bonusDamage: 0,
        bonusSecondaryDamage: 0,
        bonusRange: 0,
        range: 75
    },

    aoe:{
        type: "aoe",
        buyCost: 50,
        sellPrice : 25,
        upgradePrice: 50,
        projectiles: true,
        boosts: false,
        speed: "average",
        description: "damages in aoe",
        upgradeDescription: null,
        slow: 0,
        damage: 20,
        secondaryDamage: 12,
        upgradeDamage: 15,
        upgradeSecondaryDamage: 10,
        upgradeRange: 5,
        upgradeSlow: 0,
        bonusDamage: 0,
        bonusSecondaryDamage: 0,
        bonusRange: 0,
        range: 100
    },

    chainLaser:{
        type: "chainLaser",
        buyCost: 75,
        sellPrice : 37,
        upgradePrice: 50,
        projectiles: false,
        boosts: false,
        speed: "very fast",
        description: "shoots chaining lasers",
        upgradeDescription: null,
        slow: 0,
        damage: 1,
        secondaryDamage: 0.5,
        upgradeSecondaryDamage: 0,
        upgradeDamage: 0.25,
        upgradeRange: 5,
        upgradeSlow: 0,
        bonusDamage: 0,
        bonusSecondaryDamage: 0,
        bonusRange: 0,
        range: 120
    },

    sniper:{
        type: "sniper",
        buyCost: 75,
        sellPrice : 36,
        upgradePrice: 50,
        projectiles: true,
        boosts: false,
        speed: "slow",
        description: "shoots projectiles",
        upgradeDescription: null,
        slow: 0,
        damage: 50,
        secondaryDamage: 0,
        upgradeDamage: 20,
        upgradeSecondaryDamage: 0,
        upgradeRange: 10,
        upgradeSlow: 0,
        bonusDamage: 0,
        bonusSecondaryDamage: 0,
        bonusRange: 0,
        range: 120
    },

    boostDamage:{
        type: "boostDamage",
        buyCost: 100,
        sellPrice : 50,
        upgradePrice: 50,
        projectiles: false,
        boosts: true,
        speed: "none",
        description: "boosts towers damage",
        upgradeDescription: "increases own range",
        slow: 0,
        damage: 0,
        secondaryDamage: 0,
        upgradeSecondaryDamage: 0,
        upgradeDamage: 0,
        upgradeRange: 5,
        upgradeSlow: 0,
        bonusDamage: 0.25,
        bonusSecondaryDamage: 0.25,
        bonusRange: 0,
        range: 90
    },

    boostRange:{
        type: "boostRange",
        buyCost: 100,
        sellPrice : 50,
        upgradePrice: 50,
        projectiles: false,
        boosts: true,
        speed: "none",
        description: "boosts towers range",
        upgradeDescription: "increases range boost",
        slow: 0,
        damage: 0,
        secondaryDamage: 0,
        upgradeSecondaryDamage: 0,
        upgradeDamage: 0,
        upgradeRange: 0,
        upgradeSlow: 0,
        bonusDamage: 0,
        bonusSecondaryDamage: 0,
        bonusRange: 5,
        range: 90
    }

}

export default _TOWERS
